### ISSUE TITLE
Argument 0 for @NotNull parameter must not be null error

### ISSUE THREAD

**Issue by dkincaid** [derkork/intellij-leiningen-plugin#22]
Getting the following error when starting IntelliJ with a Leiningen project open or trying to reload the project. 

Argument 0 for @NotNull parameter of com/intellij/openapi/roots/impl/LibraryOrderEntryImpl.setScope must not be null: Argument 0 for @NotNull parameter of com/intellij/openapi/roots/impl/LibraryOrderEntryImpl.setScope must not be null
java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/intellij/openapi/roots/impl/LibraryOrderEntryImpl.setScope must not be null
    at com.intellij.openapi.roots.impl.LibraryOrderEntryImpl.setScope(LibraryOrderEntryImpl.java)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.initializeDependencies(ModuleCreationUtils.java:262)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:302)
    at de.janthomae.leiningenplugin.project.LeiningenProject$1$1.run(LeiningenProject.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:191)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:465)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:153)

**Comment by derkork** [comment]
Seems to be the same like #18
