### ISSUE TITLE
Error after upgrading to Idea 11.1.5

### ISSUE THREAD

**Issue by tmatinla** [derkork/intellij-leiningen-plugin#24]
After upgrading to the latest 11.1.x version (11.1.5 Idea Ultimate), under Leiningen Projects I see "null" project and get this error message in the Idea Event log:

IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character

My project.clj looks like this:
(defproject Project_name "1.0.0"
  :description "Project name"
  :dependencies [[clojure-csv/clojure-csv "2.0.0-alpha1"]
                 [clj-time "0.4.4"]
                 [org.clojure/data.xml "0.0.6"]]
  :source-paths "src"
  :java-source-paths "src/java"
  :test-paths "test"
  :omit-source true)

lein --version on the command prompt:
Leiningen 1.7.1 on Java 1.7.0_09 Java HotSpot(TM) 64-Bit Server VM
Environment: Win7 64-bit
Plugin version: 0.2.5

Full stack strace:
No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character
java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)
    at clojure.java.io$fn__8184$G__8179__8189.invoke(io.clj:35)
    at clojure.java.io$file.invoke(io.clj:413)
    at leiningen.core.project$absolutize.invoke(project.clj:128)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$partial$fn__4070.doInvoke(core.clj:2343)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$map$fn__4087.invoke(core.clj:2434)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.LazySeq.iterator(LazySeq.java:198)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.getPaths(ModuleCreationUtils.java:67)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.updateSourceAndResourcesPaths(ModuleCreationUtils.java:119)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.initializeModulePaths(ModuleCreationUtils.java:229)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:292)
    at de.janthomae.leiningenplugin.project.LeiningenProject$1$1.run(LeiningenProject.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:469)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:218)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:169)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:378)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:434)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:145)

**Comment by derkork** [comment]
Do you see this issue as well when using Leiningen 2? Could be related to this: https://github.com/technomancy/leiningen/issues/425 . Does this project work on the command line?

**Comment by 256BitChris** [comment]
What version of Clojure is this using?

**Comment by tmatinla** [comment]
The problem seems to be gone now. I'm not sure why so, but currently my project.clj has :java-source-paths ["src/java"] instead of :java-source-paths "src/java" and same for :source-paths and :test-paths, using a vector instead of strings. Maybe this did the trick. It did work from the command line. Not yet tested with lein 2. Project was using Clojure 1.3.0 when the problem happened.
