### ISSUE TITLE
Opened other project while Leiningen project has been initializing in the background

### ISSUE THREAD

**Issue by Unisay** [derkork/intellij-leiningen-plugin#37]
Already disposed: Already disposed
java.lang.AssertionError: Already disposed
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:289)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:55)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:40)
    at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:41)
    at com.intellij.openapi.roots.ex.ProjectRootManagerEx.getInstanceEx(ProjectRootManagerEx.java:27)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:296)
    at de.janthomae.leiningenplugin.project.LeiningenProject$1$1.run(LeiningenProject.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:400)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

**Comment by tmatinla** [comment]
Happens for me also. Inside one project it will also show different Leiningen projects and there is no way to get rid of those. I don't want mix unrelated projects... I'm unsure how to reproduce this issue, but I guess at least you need to have multiple IDEA projects (which each are based on different Leiningen projects) open at the same time. Maybe restarting IDEA with multiple open projects will cause this, but this is just a guess.
