### ISSUE TITLE
NPE when trying to import an existing project

### ISSUE THREAD

**Issue by p14n** [derkork/intellij-leiningen-plugin#40]
Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(689,570),absolute(721,794),button=1,modifiers=Button1,clickCount=1] on dialog16
java.lang.NullPointerException
    at de.janthomae.leiningenplugin.module.forms.LeiningenModuleInformationForm.getData(LeiningenModuleInformationForm.java:55)
    at de.janthomae.leiningenplugin.project.wizard.LeiningenProjectImportWizardStep.validate(LeiningenProjectImportWizardStep.java:52)
    at com.intellij.ide.util.newProjectWizard.AddModuleWizard.commitStepData(AddModuleWizard.java:223)
    at com.intellij.ide.util.newProjectWizard.AddModuleWizard.doNextAction(AddModuleWizard.java:237)
    at com.intellij.ide.wizard.AbstractWizard$5.actionPerformed(AbstractWizard.java:197)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.Component.processMouseEvent(Component.java:6414)

**Comment by juhoautio** [comment]
I stepped into the same pit. IntellijIDEA 12.1.5, OS X 10.8.5.

**Comment by 256BitChris** [comment]
Attaching sample projects that exhibit this behavior or steps to reproduce this error, rather than an exception cut and paste, will make this more likely to get fixed.
