### ISSUE TITLE
Import Failing in IntelliJ 12

### ISSUE THREAD

**Issue by gsogol** [derkork/intellij-leiningen-plugin#41]
Cloned https://github.com/aphyr/jepsen but get after pointing to project.clj in IntelliJ 12:

Could not resolve dependencies: Could not resolve dependencies
clojure.lang.ExceptionInfo: Could not resolve dependencies {:exit-code 1}
    at clojure.core$ex_info.invoke(core.clj:4227)
    at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:128)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at leiningen.core.classpath$dependency_hierarchy.invoke(classpath.clj:157)
    at de.janthomae.leiningenplugin.leiningen.LeiningenAPI$_loadDependencies.invoke(LeiningenAPI.clj:51)
    at de.janthomae.leiningenplugin.leiningen.LeiningenAPI.loadDependencies(Unknown Source)
    at de.janthomae.leiningenplugin.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:306)
    at de.janthomae.leiningenplugin.project.LeiningenProject$1$1.run(LeiningenProject.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:191)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:465)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:153)

**Comment by khneide** [comment]
having the same issue, are there any updates?
