### ISSUE TITLE
NoSuchMethodError with IntelliJ Idea 13 CE

### ISSUE THREAD

**Issue by klingtnet** [derkork/intellij-leiningen-plugin#44]
Every time I try to load a clojure project in Intellij Idea 13.1.4 the plugin crashes with a `NoSuchMethod` exception.  I am using Arch Linux with OpenJDK 1.8.0_20 and clojure 1.6.0 and Leiningen 2.4.3.
## Error message

`com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;: com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;`
## Traceback

```
com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;: com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;
java.lang.NoSuchMethodError: com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;
    at de.janthomae.leiningenplugin.project.LeiningenProject.reimport(LeiningenProject.java:133)
    at de.janthomae.leiningenplugin.project.LeiningenProjectsManager.importLeiningenProject(LeiningenProjectsManager.java:71)
    at de.janthomae.leiningenplugin.project.LeiningenProjectBuilder.commit(LeiningenProjectBuilder.java:57)
    at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:60)
    at com.intellij.projectImport.ProjectOpenProcessorBase.doOpenProject(ProjectOpenProcessorBase.java:222)
    at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:123)
    at com.intellij.ide.actions.OpenProjectAction$1.consume(OpenProjectAction.java:73)
    at com.intellij.ide.actions.OpenProjectAction$1.consume(OpenProjectAction.java:69)
    at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:133)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:111)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:89)
    at com.intellij.ide.actions.OpenProjectAction.actionPerformed(OpenProjectAction.java:69)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
    at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:170)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:133)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:313)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by derkork** [comment]
This project is no longer actively maintained by me. If you’re looking for a Clojure development environment based
on IntelliJ and with Leiningen support, check out Cursive . If you want to add new
functionality to this plugin, feel free to fork and modify it as you like.
