### ISSUE TITLE
Leiningen doesn't support latest IntelliJ version?

### ISSUE THREAD

**Issue by gnuton** [derkork/intellij-leiningen-plugin#46]
Hi,
I have just installed this plugin in my intelliJ 13 and this is what I get when I try to open project.clj file.

com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;: com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;
java.lang.NoSuchMethodError: com.intellij.openapi.module.ModifiableModuleModel.newModule(Ljava/lang/String;Lcom/intellij/openapi/module/ModuleType;)Lcom/intellij/openapi/module/Module;
    at de.janthomae.leiningenplugin.project.LeiningenProject.reimport(LeiningenProject.java:133)
    at de.janthomae.leiningenplugin.project.LeiningenProjectsManager.importLeiningenProject(LeiningenProjectsManager.java:71)
    at de.janthomae.leiningenplugin.project.LeiningenProjectBuilder.commit(LeiningenProjectBuilder.java:57)
    at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:60)
    at com.intellij.projectImport.ProjectOpenProcessorBase.doOpenProject(ProjectOpenProcessorBase.java:222)
    at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:123)
    at com.intellij.ide.actions.OpenProjectAction$1.consume(OpenProjectAction.java:73)
    at com.intellij.ide.actions.OpenProjectAction$1.consume(OpenProjectAction.java:69)
    at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:133)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:111)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:89)
    at com.intellij.ide.actions.OpenProjectAction.actionPerformed(OpenProjectAction.java:69)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:170)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:313)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by 256BitChris** [comment]
This plugin is no longer being actively supported at this time.  It was forked and brought into [Cursive Clojure](https://cursiveclojure.com/) which provides both Clojure and Leiningen support.

**Comment by gnuton** [comment]
Thanks!
