### ISSUE TITLE
com.intellij.openapi.actionSystem.impl.ChameleonAction cannot be cast to com.intellij.openapi.actionSystem.DefaultActionGroup

### ISSUE THREAD

**Issue by colceagus** [derkork/intellij-leiningen-plugin#47]
Hi, 

This happens using the latest IntellijIDEA 2016.3.4 build IU-163.12024.16

com.intellij.openapi.actionSystem.impl.ChameleonAction cannot be cast to com.intellij.openapi.actionSystem.DefaultActionGroup
java.lang.ClassCastException: com.intellij.openapi.actionSystem.impl.ChameleonAction cannot be cast to com.intellij.openapi.actionSystem.DefaultActionGroup
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigatorPanel.<init>(LeiningenProjectNavigatorPanel.java:30)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator.addPanel(LeiningenProjectNavigator.java:58)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator.access$000(LeiningenProjectNavigator.java:24)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator$1.run(LeiningenProjectNavigator.java:43)
	at com.intellij.ide.startup.impl.StartupManagerImpl.d(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:160)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:159)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:372)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:376)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:151)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:160)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$300(StartupManagerImpl.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:189)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:343)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
	at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:322)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:304)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.openapi.project.DumbServiceImpl.d(DumbServiceImpl.java:303)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:76)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Hope this helps and will be fixed soon!

All the best,
Daniel.

**Comment by derkork** [comment]
Hi,

thank you for checking out the IntelliJ Leiningen plugin. This project is
no longer actively maintained by me. If you’re looking for a Clojure
development environment based on IntelliJ and with Leiningen support, check
out Cursive . If you want to add new functionality or want to fix an issue
with this plugin, feel free to fork the code on GitHub and modify it as you
like.

You can find the plugin source at GitHub: https://github.com/
derkork/intellij-leiningen-plugin
And you can find Cursive at: https://cursive-ide.com/

Kind regards,
Jan


2017-03-06 19:26 GMT+01:00 Daniel Colceag <notifications@github.com>:
