### ISSUE TITLE
Exception load plugin

### ISSUE THREAD

**Issue by ButSoft** [derkork/intellij-leiningen-plugin#48]
idea - 2017.2.5

`com.intellij.openapi.actionSystem.impl.ChameleonAction cannot be cast to com.intellij.openapi.actionSystem.DefaultActionGroup
java.lang.ClassCastException: com.intellij.openapi.actionSystem.impl.ChameleonAction cannot be cast to com.intellij.openapi.actionSystem.DefaultActionGroup
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigatorPanel.<init>(LeiningenProjectNavigatorPanel.java:30)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator.addPanel(LeiningenProjectNavigator.java:58)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator.access$000(LeiningenProjectNavigator.java:24)
	at de.janthomae.leiningenplugin.navigator.LeiningenProjectNavigator$1.run(LeiningenProjectNavigator.java:43)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:182)
	at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:168)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:160)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:182)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$400(StartupManagerImpl.java:58)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.a(StartupManagerImpl.java:212)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:212)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:296)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.c(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by derkork** [comment]
Thank you for checking out the IntelliJ Leiningen plugin. This project is
no longer actively maintained by me. If you’re looking for a Clojure
development environment based on IntelliJ and with Leiningen support, check
out Cursive . If you want to add new functionality or want to fix an issue
with this plugin, feel free to fork the code on GitHub and modify it as you
like.

You can find the plugin source at GitHub: https://github.com/
derkork/intellij-leiningen-plugin
And you can find Cursive at: https://cursive-ide.com/
